usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/events.hh
usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/events/*
usr/include/+(ignition|gz)/common*/gz/common/events.hh
usr/include/+(ignition|gz)/common*/gz/common/events/*
usr/lib/*/cmake/+(ignition|gz)-common[0-99]-events/*
usr/lib/*/lib+(ignition|gz)-common[0-99]-events.so
usr/lib/*/pkgconfig/+(ignition|gz)-common[0-99]-events.pc
