usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/testing.hh
usr/include/+(ignition|gz)/common*/gz/common/testing.hh
usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/testing/*
usr/include/+(ignition|gz)/common*/gz/common/testing/*
usr/lib/*/cmake/+(ignition|gz)-common[0-99]-testing/*
usr/lib/*/lib+(ignition|gz)-common[0-99]-testing.so
usr/lib/*/pkgconfig/+(ignition|gz)-common[0-99]-testing.pc
