usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/geospatial.hh
usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/geospatial/*
usr/include/+(ignition|gz)/common*/gz/common/geospatial.hh
usr/include/+(ignition|gz)/common*/gz/common/geospatial/*
usr/lib/*/cmake/+(ignition|gz)-common[0-99]-geospatial/*
usr/lib/*/lib+(ignition|gz)-common[0-99]-geospatial.so
usr/lib/*/pkgconfig/+(ignition|gz)-common[0-99]-geospatial.pc
