usr/include/+(ignition|gz)/common*/+(ignition|gz)/common/profiler/*
usr/include/+(ignition|gz)/common*/gz/common/profiler/*
usr/lib/*/cmake/+(ignition|gz)-common[0-99]-profiler/*
usr/lib/*/lib+(ignition|gz)-common[0-99]-profiler.so
usr/lib/*/pkgconfig/+(ignition|gz)-common[0-99]-profiler.pc
usr/libexec/+(ignition|gz)/+(ignition|gz)-common[0-99]/*
usr/share/+(ignition|gz)/+(ignition|gz)-common[0-99]/profiler_vis/*
